### ISSUE TITLE
Check user-defined ports are available and in range

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/archethic-snap#23]
### What happened?

Right now we have the functionality to customise HTTP port and P2P port as a user-defined flag (refer #22). But we cannot allow any arbitrary port values as it maybe invalid, already allocated or is not ISP friendly. We have to make sure these user-defined ports are:

1. Within unprivileged port range.
2. Is not getting used by another system service.

### What is expected ?

ArchEthic snap will automatically detect if the ports are valid and available.

### Tasks:

- [X] Check if the ports are within unprivileged port range. If not then use the default.
- [x] Check if the ports are not occupied by another system service. If not then use the next available port.
- [x] Test the new ports for archethic-node service.
